### ISSUE TITLE
Create RSS feed for blog

### ISSUE THREAD

**Issue by faultable** [koalafyhq/landing-page#17]
All posts are live on `pages/blog/` directory and every file name representing the blog post slug.

To track all of our blog posts, we "append" the new entry into [`blog-index.json`](https://github.com/koalafyhq/landing-page/blob/master/blog-index.json), and to append new entry, you can:

- (new) ID is set via `blog post file count + 1
- For title & excerpt, you can grab it via its frontmatter
- And for `link` (on `blog-index.json`) you can set it via `/blog/${fileName}`

Based on `blog-index.json` file, you can generate the RSS feed—for example—by using [this module](https://www.npmjs.com/package/rss) but feel free to use your preferred module.

The RSS feed (and `blog-index.json`) should be generated (or checked) on [pre-push](https://git-scm.com/docs/githooks#_pre_push) via [husky](https://github.com/typicode/husky) (listed on our `devDependencies`)

If one of you is interested to take this issue, just shout it out by commenting into this issue.

**Comment by faultable** [comment]
The RSS should be generated to the `out` directory, so that it will NEVER be pushed into the remote repository

**Comment by adriantirusli** [comment]
hehehe

**Comment by faultable** [comment]
Are there any known blockers?

**Comment by faultable** [comment]
Closed by #18
